import type { MarketingLocale } from "./types"

export const toolCopy = {
  en: {
    download: "Download CSV", example: "Use worked example", exampleNote: "Illustrative example: a studio-management vendor researching independent pottery studios. These are planning assumptions, not Ceramik results.",
    replaced: "Example loaded. You can edit every field.", reset: "Inputs reset.", exported: "CSV download started. The file contains a snapshot of your current inputs.", exportError: "The download could not start. Try again or use Print or save as PDF.",
    privacy: "Your entries stay in this page. Download or print before leaving; refreshing clears them.",
    field: "Field", value: "Your criteria", help: "Guidance", exampleColumn: "Illustrative example",
    hints: ["Specify industry, operating model, and service area.", "Use conditions every acceptable account must meet.", "List useful advantages that are not mandatory.", "Name conditions that rule out an account.", "Record public, observable evidence of a problem.", "Decide which sales outcomes would change these assumptions."],
    examples: ["Independent pottery studios offering paid classes in the United States.", "Offers recurring classes; has a public website; serves adult students.", "Multiple instructors, memberships, and recurring workshops.", "Retail-only ceramics shops, closed studios, and suppliers without classes.", "Class booking relies on email; the public schedule is difficult to maintain.", "Review 20 manually checked accounts; revise criteria if fewer than 12 fit. This is a proposed test, not a measured result."],
    exampleHeading: "A completed ICP example", score: "Score", weight: "Weight", totalWeight: "Total weight", weighted: "Weighted score", invalid: "Enter weights from 0 to 100 and give at least one signal a weight above zero.",
    formula: "Score = sum of (signal × weight) ÷ sum of weights. Weights are relative; they do not need to total 100.",
    disqualifiers: "Disqualifying conditions", disqualifierHelp: "A checked condition overrides priority, even when the numeric score is high.",
    rules: ["Outside the target market or geography", "Matches an excluded business type", "A required account criterion cannot be verified"],
    excluded: "Disqualified — do not prioritize", status: "Decision", exampleMath: "Worked example: scores 90, 60, 80, 50, 40 with weights 40, 10, 20, 10, 20 produce 71/100. Review or enrich this account. Any disqualifier overrides that decision.",
    review: "Planning thresholds: 75–100 priority review; 50–74 research; below 50 hold. This score is not a purchase probability or the product’s AI score.",
  },
  pt: {
    download: "Baixar CSV", example: "Usar exemplo preenchido", exampleNote: "Exemplo ilustrativo: uma empresa de software de gestão pesquisando ateliês independentes de cerâmica. São hipóteses de planejamento, não resultados da Ceramik.",
    replaced: "Exemplo carregado. Todos os campos podem ser editados.", reset: "Campos redefinidos.", exported: "Download do CSV iniciado. O arquivo contém os valores atuais dos campos.", exportError: "Não foi possível iniciar o download. Tente novamente ou use Imprimir ou salvar em PDF.",
    privacy: "Os dados ficam nesta página. Baixe ou imprima antes de sair; atualizar a página limpa os campos.",
    field: "Campo", value: "Seus critérios", help: "Orientação", exampleColumn: "Exemplo ilustrativo",
    hints: ["Defina setor, modelo de operação e região atendida.", "Use condições obrigatórias para toda conta aceita.", "Liste vantagens úteis que não sejam obrigatórias.", "Defina condições que eliminam uma conta.", "Registre evidências públicas e observáveis do problema.", "Defina quais resultados de vendas mudariam essas hipóteses."],
    examples: ["Ateliês independentes de cerâmica com aulas pagas nos Estados Unidos.", "Oferece aulas recorrentes; tem site público; atende alunos adultos.", "Vários professores, planos de assinatura e workshops recorrentes.", "Lojas sem aulas, ateliês fechados e fornecedores de materiais.", "As reservas dependem de e-mail; a agenda pública é difícil de manter.", "Revisar 20 contas manualmente; ajustar os critérios se menos de 12 forem adequadas. É um teste proposto, não um resultado medido."],
    exampleHeading: "Um exemplo de ICP preenchido", score: "Pontuação", weight: "Peso", totalWeight: "Peso total", weighted: "Pontuação ponderada", invalid: "Informe pesos entre 0 e 100 e atribua a pelo menos um sinal um peso maior que zero.",
    formula: "Pontuação = soma de (sinal × peso) ÷ soma dos pesos. Os pesos são relativos e não precisam somar 100.",
    disqualifiers: "Condições de desqualificação", disqualifierHelp: "Uma condição marcada impede a priorização, mesmo com pontuação alta.",
    rules: ["Fora do mercado ou da região-alvo", "Corresponde a um tipo de negócio excluído", "Um critério obrigatório da conta não pode ser verificado"],
    excluded: "Desqualificada — não priorizar", status: "Decisão", exampleMath: "Exemplo: notas 90, 60, 80, 50, 40 com pesos 40, 10, 20, 10, 20 resultam em 71/100. Revise ou enriqueça a conta. Qualquer desqualificador prevalece sobre essa decisão.",
    review: "Faixas de planejamento: 75–100 revisão prioritária; 50–74 pesquisa; abaixo de 50 aguardar. Não é uma probabilidade de compra nem a pontuação de IA do produto.",
  },
  es: {
    download: "Descargar CSV", example: "Usar ejemplo completo", exampleNote: "Ejemplo ilustrativo: un proveedor de software de gestión investigando talleres independientes de cerámica. Son supuestos de planificación, no resultados de Ceramik.",
    replaced: "Ejemplo cargado. Puedes editar todos los campos.", reset: "Campos restablecidos.", exported: "Descarga del CSV iniciada. El archivo contiene los valores actuales de los campos.", exportError: "No se pudo iniciar la descarga. Inténtalo de nuevo o usa Imprimir o guardar como PDF.",
    privacy: "Los datos permanecen en esta página. Descarga o imprime antes de salir; actualizar la página borra los campos.",
    field: "Campo", value: "Tus criterios", help: "Orientación", exampleColumn: "Ejemplo ilustrativo",
    hints: ["Define el sector, modelo operativo y zona atendida.", "Usa condiciones que toda cuenta aceptable deba cumplir.", "Enumera ventajas útiles que no sean obligatorias.", "Define condiciones que descarten una cuenta.", "Registra evidencia pública y observable del problema.", "Define qué resultados comerciales cambiarían estos supuestos."],
    examples: ["Talleres independientes de cerámica con clases de pago en Estados Unidos.", "Ofrece clases recurrentes; tiene web pública; atiende a estudiantes adultos.", "Varios profesores, membresías y talleres recurrentes.", "Tiendas sin clases, talleres cerrados y proveedores de materiales.", "Las reservas dependen del correo; el calendario público es difícil de mantener.", "Revisar 20 cuentas manualmente; ajustar los criterios si menos de 12 encajan. Es una prueba propuesta, no un resultado medido."],
    exampleHeading: "Un ejemplo de ICP completo", score: "Puntuación", weight: "Peso", totalWeight: "Peso total", weighted: "Puntuación ponderada", invalid: "Introduce pesos entre 0 y 100 y asigna al menos a una señal un peso superior a cero.",
    formula: "Puntuación = suma de (señal × peso) ÷ suma de pesos. Los pesos son relativos; no necesitan sumar 100.",
    disqualifiers: "Condiciones de descalificación", disqualifierHelp: "Una condición marcada anula la prioridad, incluso con una puntuación alta.",
    rules: ["Fuera del mercado o la zona objetivo", "Corresponde a un tipo de negocio excluido", "No se puede verificar un criterio obligatorio de la cuenta"],
    excluded: "Descalificada — no priorizar", status: "Decisión", exampleMath: "Ejemplo: puntuaciones 90, 60, 80, 50, 40 con pesos 40, 10, 20, 10, 20 dan 71/100. Revisa o enriquece la cuenta. Cualquier descalificador prevalece sobre esa decisión.",
    review: "Umbrales de planificación: 75–100 revisión prioritaria; 50–74 investigación; menos de 50 esperar. No es una probabilidad de compra ni la puntuación de IA del producto.",
  },
} satisfies Record<MarketingLocale, Record<string, string | string[]>>
