export const BUSINESS_CATEGORIES = [
  "Accounting & Finance",
  "Agriculture",
  "Architecture & Design",
  "Automotive",
  "Beauty & Wellness",
  "Construction",
  "Consulting",
  "Dental & Orthodontics",
  "E-commerce",
  "Education & Training",
  "Energy & Utilities",
  "Entertainment & Media",
  "Events & Catering",
  "Fashion & Apparel",
  "Fitness & Sports",
  "Food & Beverage",
  "Healthcare",
  "Home Services",
  "Hospitality & Tourism",
  "Insurance",
  "IT & Software",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing",
  "Marketing & Advertising",
  "Non-Profit",
  "Pet Services",
  "Photography & Videography",
  "Real Estate",
  "Recruitment & HR",
  "Restaurant & Bar",
  "Retail",
  "SaaS",
  "Security",
  "Telecommunications",
  "Veterinary",
  "Other",
] as const

export type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number]

const translations: Record<string, Record<BusinessCategory, string>> = {
  pt: {
    "Accounting & Finance": "Contabilidade e Finanças",
    "Agriculture": "Agricultura",
    "Architecture & Design": "Arquitetura e Design",
    "Automotive": "Automotivo",
    "Beauty & Wellness": "Beleza e Bem-estar",
    "Construction": "Construção",
    "Consulting": "Consultoria",
    "Dental & Orthodontics": "Odontologia e Ortodontia",
    "E-commerce": "E-commerce",
    "Education & Training": "Educação e Treinamento",
    "Energy & Utilities": "Energia e Utilidades",
    "Entertainment & Media": "Entretenimento e Mídia",
    "Events & Catering": "Eventos e Buffet",
    "Fashion & Apparel": "Moda e Vestuário",
    "Fitness & Sports": "Fitness e Esportes",
    "Food & Beverage": "Alimentos e Bebidas",
    "Healthcare": "Saúde",
    "Home Services": "Serviços Residenciais",
    "Hospitality & Tourism": "Hotelaria e Turismo",
    "Insurance": "Seguros",
    "IT & Software": "TI e Software",
    "Legal Services": "Serviços Jurídicos",
    "Logistics & Transportation": "Logística e Transporte",
    "Manufacturing": "Manufatura",
    "Marketing & Advertising": "Marketing e Publicidade",
    "Non-Profit": "Sem Fins Lucrativos",
    "Pet Services": "Serviços para Pets",
    "Photography & Videography": "Fotografia e Videografia",
    "Real Estate": "Imóveis",
    "Recruitment & HR": "Recrutamento e RH",
    "Restaurant & Bar": "Restaurante e Bar",
    "Retail": "Varejo",
    "SaaS": "SaaS",
    "Security": "Segurança",
    "Telecommunications": "Telecomunicações",
    "Veterinary": "Veterinária",
    "Other": "Outro",
  },
  es: {
    "Accounting & Finance": "Contabilidad y Finanzas",
    "Agriculture": "Agricultura",
    "Architecture & Design": "Arquitectura y Diseño",
    "Automotive": "Automotriz",
    "Beauty & Wellness": "Belleza y Bienestar",
    "Construction": "Construcción",
    "Consulting": "Consultoría",
    "Dental & Orthodontics": "Odontología y Ortodoncia",
    "E-commerce": "E-commerce",
    "Education & Training": "Educación y Capacitación",
    "Energy & Utilities": "Energía y Servicios Públicos",
    "Entertainment & Media": "Entretenimiento y Medios",
    "Events & Catering": "Eventos y Catering",
    "Fashion & Apparel": "Moda y Vestimenta",
    "Fitness & Sports": "Fitness y Deportes",
    "Food & Beverage": "Alimentos y Bebidas",
    "Healthcare": "Salud",
    "Home Services": "Servicios para el Hogar",
    "Hospitality & Tourism": "Hotelería y Turismo",
    "Insurance": "Seguros",
    "IT & Software": "TI y Software",
    "Legal Services": "Servicios Legales",
    "Logistics & Transportation": "Logística y Transporte",
    "Manufacturing": "Manufactura",
    "Marketing & Advertising": "Marketing y Publicidad",
    "Non-Profit": "Sin Fines de Lucro",
    "Pet Services": "Servicios para Mascotas",
    "Photography & Videography": "Fotografía y Videografía",
    "Real Estate": "Bienes Raíces",
    "Recruitment & HR": "Reclutamiento y RRHH",
    "Restaurant & Bar": "Restaurante y Bar",
    "Retail": "Comercio Minorista",
    "SaaS": "SaaS",
    "Security": "Seguridad",
    "Telecommunications": "Telecomunicaciones",
    "Veterinary": "Veterinaria",
    "Other": "Otra",
  },
}

/** Get categories with translated labels. Value is always the English key (for DB storage). */
export function getTranslatedCategories(locale: string): { value: BusinessCategory; label: string }[] {
  const t = translations[locale]
  return BUSINESS_CATEGORIES.map((cat) => ({
    value: cat,
    label: t?.[cat] || cat,
  }))
}
